"""Fix budget mapper

Revision ID: 1ed6cc81a149
Revises: d16a3fda7abb
Create Date: 2025-01-25 10:23:30.118355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed6cc81a149'
down_revision: Union[str, None] = 'd16a3fda7abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
