"""Add user session information

Revision ID: 68503f772a5a
Revises: 7d600b951d3d
Create Date: 2025-01-09 12:47:44.192985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68503f772a5a'
down_revision: Union[str, None] = '7d600b951d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('eb_session_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('valid_until', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'valid_until')
    op.drop_column('user', 'eb_session_id')
    # ### end Alembic commands ###
