"""Add balance table

Revision ID: 8a9780d18cf7
Revises: e4be3c951934
Create Date: 2025-01-22 22:02:53.258529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9780d18cf7'
down_revision: Union[str, None] = 'e4be3c951934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance_currency', sa.String(), nullable=False),
    sa.Column('balance_amount', sa.String(), nullable=False),
    sa.Column('balance_type', sa.String(), nullable=False),
    sa.Column('last_change_date_time', sa.String(), nullable=True),
    sa.Column('reference_date_time', sa.String(), nullable=True),
    sa.Column('last_commited_transaction', sa.String(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_id'), 'balance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_id'), table_name='balance')
    op.drop_table('balance')
    # ### end Alembic commands ###
