"""Fix account nullabilities

Revision ID: 936896c3bd07
Revises: e436d7604754
Create Date: 2025-01-20 20:48:51.818482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936896c3bd07'
down_revision: Union[str, None] = 'e436d7604754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('account', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('account', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('account', 'identification_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'identification_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('account', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
