"""Add Account table

Revision ID: 9a88f1314ecf
Revises: e5d9dba8aa13
Create Date: 2025-01-09 13:07:56.105982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a88f1314ecf'
down_revision: Union[str, None] = 'e5d9dba8aa13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('all_account_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('account_servicer', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('cash_account_type', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('psu_status', sa.String(), nullable=True),
    sa.Column('credit_limit', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('identification_hash', sa.String(), nullable=False),
    sa.Column('identification_hashes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
