"""Rearrange properties of a transaction

Revision ID: db92b04e8ed5
Revises: eca07c805621
Create Date: 2025-06-02 16:43:46.476555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db92b04e8ed5'
down_revision: Union[str, None] = 'eca07c805621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'entry_reference', new_column_name='reference')
    op.add_column('transaction', sa.Column('transaction_date', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('remittance_information', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('merchant_category_code', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('debtor_name', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('bank_transaction_code', sa.String(), nullable=True))
    op.alter_column('transaction', 'booking_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transaction', 'transaction_currency')
    op.drop_column('transaction', 'transaction_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('transaction_amount', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('transaction', 'reference', new_column_name='entry_reference')
    op.add_column('transaction', sa.Column('transaction_currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('transaction', 'booking_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transaction', 'bank_transaction_code')
    op.drop_column('transaction', 'debtor_name')
    op.drop_column('transaction', 'merchant_category_code')
    op.drop_column('transaction', 'remittance_information')
    op.drop_column('transaction', 'currency')
    op.drop_column('transaction', 'amount')
    op.drop_column('transaction', 'transaction_date')
    op.drop_column('transaction', 'reference')
    # ### end Alembic commands ###
