"""Add transactions table

Revision ID: de8ed2b40696
Revises: 8a9780d18cf7
Create Date: 2025-01-22 22:37:32.677089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8ed2b40696'
down_revision: Union[str, None] = '8a9780d18cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('entry_reference', sa.String(), nullable=False),
    sa.Column('transaction_amount', sa.String(), nullable=False),
    sa.Column('transaction_currency', sa.String(), nullable=False),
    sa.Column('creditor_name', sa.String(), nullable=True),
    sa.Column('credit_debit_indicator', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('booking_date', sa.String(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.add_column('balance', sa.Column('reference_date', sa.String(), nullable=True))
    op.add_column('balance', sa.Column('last_committed_transaction', sa.String(), nullable=True))
    op.drop_column('balance', 'reference_date_time')
    op.drop_column('balance', 'last_commited_transaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('last_commited_transaction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('balance', sa.Column('reference_date_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('balance', 'last_committed_transaction')
    op.drop_column('balance', 'reference_date')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
