"""Add nullability on transaction properties and remove spending predictions table

Revision ID: f347b5eba6dd
Revises: add_ml_results
Create Date: 2025-06-05 17:10:37.347145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f347b5eba6dd'
down_revision: Union[str, None] = 'add_ml_results'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spending_predictions_prediction_date', table_name='spending_predictions')
    op.drop_index('ix_spending_predictions_user_id', table_name='spending_predictions')
    op.drop_table('spending_predictions')
    op.drop_index('ix_transaction_category', table_name='transaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transaction_category', 'transaction', ['category'], unique=False)
    op.create_table('spending_predictions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prediction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('target_period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('target_period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('predicted_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='spending_predictions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='spending_predictions_pkey')
    )
    op.create_index('ix_spending_predictions_user_id', 'spending_predictions', ['user_id'], unique=False)
    op.create_index('ix_spending_predictions_prediction_date', 'spending_predictions', ['prediction_date'], unique=False)
    # ### end Alembic commands ###
